### ISSUE TITLE
Looking forward to the paper!

### ISSUE THREAD

**Issue by LionTao** [ZJU-DAILY/ST2Vec#1]
Hi, I'm very interested in your awesome work.
But I did my best to do the search and still couldn't find your paper.
Could you tell me whether it is because the paper is still under review?

**Comment by Scottdyt** [comment]
Thanks for your interest, however, our paper is under review, we would like to release the arxiv as soon as possible. Stay tune!

**Comment by Scottdyt** [comment]
We have release the Arxiv version: https://arxiv.org/abs/2112.09339
Check it out :)

**Comment by LionTao** [comment]
Awesome! Thank you for your great work!
